### ISSUE TITLE
Avoid warnings in Symfony 2.8 by using quotes for declaring dependencies.

### ISSUE THREAD

**Issue by jcchavezs** [LeaseWeb/LswSecureControllerBundle#9]
In ```Lsw/SecureControllerBundle/Resources/config/services.yml```:

```
services:
    secure_controller.controller_listener:
        class: %secure_controller.controller_listener.class%
        arguments: [@annotation_reader,@security.context]
```

Both ```@annotation_reader``` and ```@security.context``` must be quoted for avoiding warnings in Symfony 2.8.
